document.addEventListener("DOMContentLoaded", () => {
  const countries = [
    { en: "Afghanistan", sw: "Afghanistani" },
    { en: "Albania", sw: "Albania" },
    { en: "Algeria", sw: "Aljeria" },
    { en: "Andorra", sw: "Andora" },
    { en: "Angola", sw: "Angola" },
    { en: "Antigua and Barbuda", sw: "Antigua na Barbuda" },
    { en: "Argentina", sw: "Ajentina" },
    { en: "Armenia", sw: "Armenia" },
    { en: "Australia", sw: "Australia" },
    { en: "Austria", sw: "Austia" },
    { en: "Azerbaijan", sw: "Azerbaijan" },
    { en: "Bahamas", sw: "Bahama" },
    { en: "Bahrain", sw: "Bahrain" },
    { en: "Bangladesh", sw: "Bangladeshi" },
    { en: "Barbados", sw: "Barbados" },
    { en: "Belarus", sw: "Belarusi" },
    { en: "Belgium", sw: "Ubelgiji" },
    { en: "Belize", sw: "Belize" },
    { en: "Benin", sw: "Beni" },
    { en: "Bhutan", sw: "Bhutani" },
    { en: "Bolivia", sw: "Bolivia" },
    { en: "Bosnia and Herzegovina", sw: "Bosnia na Herzegovina" },
    { en: "Botswana", sw: "Botswana" },
    { en: "Brazil", sw: "Brazili" },
    { en: "Brunei", sw: "Brunei" },
    { en: "Bulgaria", sw: "Bulgaria" },
    { en: "Burkina Faso", sw: "Burkina Faso" },
    { en: "Burundi", sw: "Burundi" },
    { en: "Cambodia", sw: "Kambodia" },
    { en: "Cameroon", sw: "Kameruni" },
    { en: "Canada", sw: "Kanada" },
    { en: "Cape Verde", sw: "Kepu Verdi" },
    { en: "Central African Republic", sw: "Jamhuri ya Afrika ya Kati" },
    { en: "Chad", sw: "Chadi" },
    { en: "Chile", sw: "Chile" },
    { en: "China", sw: "China" },
    { en: "Colombia", sw: "Kolombia" },
    { en: "Comoros", sw: "Komoro" },
    { en: "Congo (Brazzaville)", sw: "Kongo (Brazzaville)" },
    { en: "Congo (Kinshasa)", sw: "Kongo (Kinshasa)" },
    { en: "Costa Rica", sw: "Costa Rica" },
    { en: "Croatia", sw: "Kroeshia" },
    { en: "Cuba", sw: "Kuba" },
    { en: "Cyprus", sw: "Kuprosi" },
    { en: "Czech Republic", sw: "Jamhuri ya Cheki" },
    { en: "Denmark", sw: "Denmaki" },
    { en: "Djibouti", sw: "Jibuti" },
    { en: "Dominica", sw: "Dominika" },
    { en: "Dominican Republic", sw: "Jamhuri ya Dominika" },
    { en: "Ecuador", sw: "Ekwado" },
    { en: "Egypt", sw: "Misri" },
    { en: "El Salvador", sw: "El Salvador" },
    { en: "Equatorial Guinea", sw: "Ginekweta" },
    { en: "Eritrea", sw: "Eritrea" },
    { en: "Estonia", sw: "Estonia" },
    { en: "Eswatini", sw: "Eswatini" },
    { en: "Ethiopia", sw: "Ethiopia" },
    { en: "Fiji", sw: "Fiji" },
    { en: "Finland", sw: "Ufini" },
    { en: "France", sw: "Ufaransa" },
    { en: "Gabon", sw: "Gaboni" },
    { en: "Gambia", sw: "Gambia" },
    { en: "Georgia", sw: "Jojia" },
    { en: "Germany", sw: "Ujerumani" },
    { en: "Ghana", sw: "Ghana" },
    { en: "Greece", sw: "Ugiriki" },
    { en: "Grenada", sw: "Grenada" },
    { en: "Guatemala", sw: "Guatemala" },
    { en: "Guinea", sw: "Gine" },
    { en: "Guinea-Bissau", sw: "Gine-Bissau" },
    { en: "Guyana", sw: "Guyana" },
    { en: "Haiti", sw: "Haiti" },
    { en: "Honduras", sw: "Hondurasi" },
    { en: "Hungary", sw: "Hungaria" },
    { en: "Iceland", sw: "Aislandi" },
    { en: "India", sw: "India" },
    { en: "Indonesia", sw: "Indoneshia" },
    { en: "Iran", sw: "Iran" },
    { en: "Iraq", sw: "Iraqi" },
    { en: "Ireland", sw: "Ayalandi" },
    { en: "Israel", sw: "Israeli" },
    { en: "Italy", sw: "Italia" },
    { en: "Jamaica", sw: "Jamaika" },
    { en: "Japan", sw: "Japani" },
    { en: "Jordan", sw: "Jordan" },
    { en: "Kazakhstan", sw: "Kazakistani" },
    { en: "Kenya", sw: "Kenya" },
    { en: "Kiribati", sw: "Kiribati" },
    { en: "Kuwait", sw: "Kuwaiti" },
    { en: "Kyrgyzstan", sw: "Kirigizistani" },
    { en: "Laos", sw: "Laosi" },
    { en: "Latvia", sw: "Latvia" },
    { en: "Lebanon", sw: "Lebanoni" },
    { en: "Lesotho", sw: "Lesotho" },
    { en: "Liberia", sw: "Liberia" },
    { en: "Libya", sw: "Libya" },
    { en: "Liechtenstein", sw: "Liechtenstein" },
    { en: "Lithuania", sw: "Lithuania" },
    { en: "Luxembourg", sw: "Lasembagi" },
    { en: "Madagascar", sw: "Madagaska" },
    { en: "Malawi", sw: "Malawi" },
    { en: "Malaysia", sw: "Malesia" },
    { en: "Maldives", sw: "Maldivi" },
    { en: "Mali", sw: "Mali" },
    { en: "Malta", sw: "Malta" },
    { en: "Marshall Islands", sw: "Visiwa vya Marshal" },
    { en: "Mauritania", sw: "Mauritania" },
    { en: "Mauritius", sw: "Mauritius" },
    { en: "Mexico", sw: "Meksiko" },
    { en: "Micronesia", sw: "Mikronesia" },
    { en: "Moldova", sw: "Moldova" },
    { en: "Monaco", sw: "Monako" },
    { en: "Mongolia", sw: "Mongolia" },
    { en: "Montenegro", sw: "Montenegro" },
    { en: "Morocco", sw: "Moroko" },
    { en: "Mozambique", sw: "Msumbiji" },
    { en: "Myanmar", sw: "Myanmar" },
    { en: "Namibia", sw: "Namibia" },
    { en: "Nauru", sw: "Nauru" },
    { en: "Nepal", sw: "Nepali" },
    { en: "Netherlands", sw: "Uholanzi" },
    { en: "New Zealand", sw: "Nyuzilandi" },
    { en: "Nicaragua", sw: "Nikaragwa" },
    { en: "Niger", sw: "Niger" },
    { en: "Nigeria", sw: "Nigeria" },
    { en: "North Korea", sw: "Korea Kaskazini" },
    { en: "North Macedonia", sw: "Masedonia Kaskazini" },
    { en: "Norway", sw: "Norwe" },
    { en: "Oman", sw: "Omani" },
    { en: "Pakistan", sw: "Pakistani" },
    { en: "Palau", sw: "Palau" },
    { en: "Panama", sw: "Panama" },
    { en: "Papua New Guinea", sw: "Papua Nyukini" },
    { en: "Paraguay", sw: "Paragwai" },
    { en: "Peru", sw: "Peru" },
    { en: "Philippines", sw: "Ufilipino" },
    { en: "Poland", sw: "Polandi" },
    { en: "Portugal", sw: "Ureno" },
    { en: "Qatar", sw: "Qatar" },
    { en: "Romania", sw: "Romania" },
    { en: "Russia", sw: "Urusi" },
    { en: "Rwanda", sw: "Rwanda" },
    { en: "Saint Kitts and Nevis", sw: "Saint Kitts na Nevis" },
    { en: "Saint Lucia", sw: "Saint Lucia" },
    { en: "Saint Vincent and the Grenadines", sw: "Saint Vincent na Grenadines" },
    { en: "Samoa", sw: "Samoa" },
    { en: "San Marino", sw: "San Marino" },
    { en: "Sao Tome and Principe", sw: "Sao Tome na Principe" },
    { en: "Saudi Arabia", sw: "Saudi Arabia" },
    { en: "Senegal", sw: "Senegal" },
    { en: "Serbia", sw: "Serbia" },
    { en: "Seychelles", sw: "Seychelles" },
    { en: "Sierra Leone", sw: "Sierra Leone" },
    { en: "Singapore", sw: "Singapore" },
    { en: "Slovakia", sw: "Slovakia" },
    { en: "Slovenia", sw: "Slovenia" },
    { en: "Solomon Islands", sw: "Visiwa vya Solomon" },
    { en: "Somalia", sw: "Somalia" },
    { en: "South Africa", sw: "Afrika Kusini" },
    { en: "South Korea", sw: "Korea Kusini" },
    { en: "South Sudan", sw: "Sudan Kusini" },
    { en: "Spain", sw: "Hispania" },
    { en: "Sri Lanka", sw: "Sri Lanka" },
    { en: "Sudan", sw: "Sudan" },
    { en: "Suriname", sw: "Suriname" },
    { en: "Sweden", sw: "Uswidi" },
    { en: "Switzerland", sw: "Uswisi" },
    { en: "Syria", sw: "Syria" },
    { en: "Taiwan", sw: "Taiwan" },
    { en: "Tajikistan", sw: "Tajikistani" },
    { en: "Tanzania", sw: "Tanzania" },
    { en: "Thailand", sw: "Tailandi" },
    { en: "Timor-Leste", sw: "Timor-Leste" },
    { en: "Togo", sw: "Togo" },
    { en: "Tonga", sw: "Tonga" },
    { en: "Trinidad and Tobago", sw: "Trinidad na Tobago" },
    { en: "Tunisia", sw: "Tunisia" },
    { en: "Turkey", sw: "Uturuki" },
    { en: "Turkmenistan", sw: "Turkmenistani" },
    { en: "Tuvalu", sw: "Tuvalu" },
    { en: "Uganda", sw: "Uganda" },
    { en: "Ukraine", sw: "Ukraine" },
    { en: "United Arab Emirates", sw: "Falme za Kiarabu" },
    { en: "United Kingdom", sw: "Uingereza" },
    { en: "United States", sw: "Marekani" },
    { en: "Uruguay", sw: "Uruguay" },
    { en: "Uzbekistan", sw: "Uzbekistani" },
    { en: "Vanuatu", sw: "Vanuatu" },
    { en: "Vatican City", sw: "Mji wa Vatikani" },
    { en: "Venezuela", sw: "Venezuela" },
    { en: "Vietnam", sw: "Vietnamu" },
    { en: "Yemen", sw: "Yemeni" },
    { en: "Zambia", sw: "Zambia" },
    { en: "Zimbabwe", sw: "Zimbabwe" }
  ];

  const countrySelect = document.getElementById("country-select");
  if(!countrySelect) return;

  // Keep first option
  const firstOption = countrySelect.querySelector("option");
  firstOption.dataset.en = "Select Country";
  firstOption.dataset.sw = "Chagua Nchi";

  // Add countries
  countries.forEach(c => {
    const opt = document.createElement("option");
    opt.value = c.en;
    opt.textContent = c.en;
    opt.dataset.en = c.en;
    opt.dataset.sw = c.sw;
    countrySelect.appendChild(opt);
  });

  // Language switch
  const langSelect = document.getElementById("languageSelect");
  if(langSelect){
    langSelect.addEventListener("change", () => {
      const lang = langSelect.value;
      document.querySelectorAll("[data-en]").forEach(el => {
        const text = lang === "sw" ? el.dataset.sw : el.dataset.en;
        if(el.tagName === "INPUT" || el.tagName === "TEXTAREA"){
          if(el.type === "submit") el.value = text;
          else el.placeholder = text;
        } else if(el.tagName === "OPTION"){
          el.textContent = text;
        } else {
          el.textContent = text;
        }
      });
    });
  }
});
